version: "3.3"
services:
  oda-cc-symphonypaintsr:
    build: .
    image: "bom.ocir.io/bmrdvxoeeutl/avauat-oke/bg-doc-uploader:1.0"
    container_name: "oda-cc-symphonypaintsr"
    command: "npm start"
    ports:
      - 3000:3000
